name: Run Playwright Test on Friday

on:
  schedule:
    # ריצה כל יום שישי בשעה 13:00 UTC (16:00 שעון ישראל בקיץ)
    - cron: '0 13 * * 5'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run tests
        run: pytest tests/test_topup.py
