name: Run Playwright Test Daily at 16:00 Israel Time

on:
  schedule:
    - cron: '0 13 * * *'  # 16:00 ישראל
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run tests and capture result
        id: run_tests
        run: |
          set +e
          pytest tests/test_topup.py > result.log
          EXIT_CODE=$?
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
          echo "==== Test Output ===="
          cat result.log
          echo "====================="
          exit $EXIT_CODE

      - name: Send Telegram message
        if: always()
        env:
          TELEGRAMTOKEN: ${{ secrets.TELEGRAMTOKEN }}
          TELEGRAMCHATID: ${{ secrets.TELEGRAMCHATID }}
        run: |
          if [ "${{ steps.run_tests.outputs.exit_code }}" == "0" ]; then
            TEXT="✅ הטעינה של הסיבוס בוצעה בהצלחה (הטסט עבר)"
          else
            TEXT="❌  לא בוצעה טעינה לסיבוס"
          fi
          curl -s "https://api.telegram.org/bot${TELEGRAMTOKEN}/sendMessage" \
            -d "chat_id=${TELEGRAMCHATID}" \
            --data-urlencode "text=${TEXT}"
