name: Run Playwright Test - Weekday & Friday Times

on:
  schedule:
    - cron: '0 9 * * 0-4'   # ראשון עד חמישי, 12:00 ישראל (09:00 UTC)
    - cron: '0 10 * * 5'    # שישי בלבד, 13:00 ישראל (10:00 UTC)
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run tests and capture result
        id: run_tests
        run: |
          set +e
          pytest tests/test_topup.py > result.log
          EXIT_CODE=$?
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
          cat result.log
          exit $EXIT_CODE

      - name: Send Telegram message
        if: always()
        env:
          TELEGRAMTOKEN: ${{ secrets.TELEGRAMTOKEN }}
          TELEGRAMCHATID: ${{ secrets.TELEGRAMCHATID }}
        run: |
          DATE=$(TZ=Asia/Jerusalem date +"%Y-%m-%d")
          DAY_NAME=$(TZ=Asia/Jerusalem date +"%A" | sed 's/Monday/שני/;s/Tuesday/שלישי/;s/Wednesday/רביעי/;s/Thursday/חמישי/;s/Friday/שישי/;s/Saturday/שבת/;s/Sunday/ראשון/')
          if [ "${{ steps.run_tests.outputs.exit_code }}" == "0" ]; then
            STATUS="✅ טעינת סיבוס בוצעה בהצלחה"
          else
            STATUS="❌ טעינת סיבוס נכשלה"
          fi
          TEXT="$STATUS ביום $DAY_NAME, תאריך: $DATE"
          curl -s "https://api.telegram.org/bot${TELEGRAMTOKEN}/sendMessage" \
            -d "chat_id=${TELEGRAMCHATID}" \
            --data-urlencode "text=${TEXT}"
