name: Run Playwright Test on Schedule

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 0-4'  # ראשון עד חמישי
    - cron: '0 12 * * 5'    # שישי
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Show event trigger
        run: echo "Triggered by ${{ github.event_name }}"

      - name: Run tests and capture result
        id: run_tests
        env:
          # סודות קיימים למערכת סיבוס
          HAHISHOOK_USERNAME: ${{ secrets.HAHISHOOK_USERNAME }}
          HAHISHOOK_PASSWORD: ${{ secrets.HAHISHOOK_PASSWORD }}
          CIBUS_USERNAME: ${{ secrets.CIBUS_USERNAME }}
          CIBUS_PASSWORD: ${{ secrets.CIBUS_PASSWORD }}
          CIBUS_COMPANY: ${{ secrets.CIBUS_COMPANY }}

          # סודות לקריאת OTP מהמייל
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          EMAIL_IMAP_SERVER: ${{ secrets.EMAIL_IMAP_SERVER }}
          EMAIL_IMAP_PORT: ${{ secrets.EMAIL_IMAP_PORT }}
        run: |
          set +e
          pytest tests/test_topup.py > result.log
          EXIT_CODE=$?
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
          cat result.log
          exit $EXIT_CODE

      - name: Send Telegram message
        if: always()
        env:
          TELEGRAMTOKEN: ${{ secrets.TELEGRAMTOKEN }}
          TELEGRAMCHATID: ${{ secrets.TELEGRAMCHATID }}
        run: |
          DATE=$(TZ=Asia/Jerusalem date +"%Y-%m-%d")
          DAY_NAME=$(TZ=Asia/Jerusalem date +"%A" | sed 's/Monday/שני/;s/Tuesday/שלישי/;s/Wednesday/רביעי/;s/Thursday/חמישי/;s/Friday/שישי/;s/Saturday/שבת/;s/Sunday/ראשון/')
          if [ "${{ steps.run_tests.outputs.exit_code }}" == "0" ]; then
            STATUS="✅ טעינת סיבוס בוצעה בהצלחה"
          else
            STATUS="❌ טעינת סיבוס נכשלה"
          fi
          TEXT="$STATUS ביום $DAY_NAME, תאריך: $DATE"
          curl -s "https://api.telegram.org/bot${TELEGRAMTOKEN}/sendMessage" \
            -d "chat_id=${TELEGRAMCHATID}" \
            --data-urlencode "text=${TEXT}"
